### ISSUE TITLE
Impossible to try the example

### ISSUE THREAD

**Issue by EduardoAC** [apiaryio/dredd-example#68]
## Problem

I run the following commands
```
npm install
npm run test:openapi2
```

Example not working

I don't have running mongoDb since there is not image or database schema and data for it 

Following trace can be found
```
Apiary API Key or API Project Subdomain were not provided.
Configure Dredd to be able to save test reports alongside your Apiary API project:
https://dredd.org/en/latest/how-to-guides/#using-apiary-reporter-and-apiary-tests

error: TypeError: Cannot read property 'collection' of undefined
    at hooks.afterEach (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:44:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: GET (200) / duration: NaNms
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.before (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:57:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: GET (200) /gists/42 duration: NaNms
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.afterEach (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:44:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: GET (200) /gists/42 duration: NaNms
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.before (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:63:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: PATCH (200) /gists/42 duration: NaNms
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.afterEach (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:44:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: PATCH (200) /gists/42 duration: NaNms
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
warn: DELETE (204) /gists/42 HTTP 204 and 205 responses must not include a message body: https://tools.ietf.org/html/rfc7231#section-6.3
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.afterEach (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:44:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: DELETE (204) /gists/42 duration: NaNms
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.before (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:69:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: GET (200) /gists?since=0 duration: NaNms
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.afterEach (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:44:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: GET (200) /gists?since=0 duration: NaNms
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.afterEach (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:44:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: POST (201) /gists?since=0 duration: NaNms
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
warn: PUT (204) /gists/42/star HTTP 204 and 205 responses must not include a message body: https://tools.ietf.org/html/rfc7231#section-6.3
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.afterEach (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:44:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: PUT (204) /gists/42/star duration: NaNms
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
warn: DELETE (204) /gists/42/star HTTP 204 and 205 responses must not include a message body: https://tools.ietf.org/html/rfc7231#section-6.3
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.afterEach (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:44:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: DELETE (204) /gists/42/star duration: NaNms
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.before (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:75:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: GET (200) /gists/42/star duration: NaNms
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/eduardoac/projects/dredd-example/node_modules/express-mongo-db/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
error: TypeError: Cannot read property 'collection' of undefined
    at hooks.afterEach (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:44:6)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: GET (200) /gists/42/star duration: NaNms
error: TypeError: Cannot read property 'close' of undefined
    at hooks.afterAll (/Users/eduardoac/projects/dredd-example/apiblueprint/hooks.js:37:10)
    at TransactionRunner.runHook (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:218:7)
    at runHookWithData (/Users/eduardoac/projects/dredd-example/node_modules/dredd/lib/TransactionRunner.js:169:16)
    at eachfn (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:247:13)
    at replenish (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:444:21)
    at /Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:449:13
    at _asyncMap (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:245:16)
    at mapLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:1767:16)
    at awaitable(mapLimit) (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:208:32)
    at timesLimit (/Users/eduardoac/projects/dredd-example/node_modules/async/dist/async.js:4219:16)
error: undefined duration: NaNms
info: Displaying failed tests...
fail: GET (200) / duration: NaNms
fail: Gist Fox API Root > Retrieve the Entry Point
request: 
method: GET
uri: /
headers: 
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 



fail: GET (200) /gists/42 duration: NaNms
fail: Gist > Retrieve a Single Gist
request: 
method: GET
uri: /gists/42
headers: 
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 



fail: GET (200) /gists/42 duration: NaNms
fail: Gist > Retrieve a Single Gist
request: 
method: GET
uri: /gists/42
headers: 
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 



fail: PATCH (200) /gists/42 duration: NaNms
fail: Gist > Edit a Gist
request: 
method: PATCH
uri: /gists/42
headers: 
    Content-Type: application/json
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 
{
  "content": "Updated content..."
}


fail: PATCH (200) /gists/42 duration: NaNms
fail: Gist > Edit a Gist
request: 
method: PATCH
uri: /gists/42
headers: 
    Content-Type: application/json
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 
{
  "content": "Updated content..."
}


fail: DELETE (204) /gists/42 duration: NaNms
fail: Gist > Delete a Gist
request: 
method: DELETE
uri: /gists/42
headers: 
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 



fail: GET (200) /gists?since=0 duration: NaNms
fail: Gists Collection > List All Gists
request: 
method: GET
uri: /gists?since=0
headers: 
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 



fail: GET (200) /gists?since=0 duration: NaNms
fail: Gists Collection > List All Gists
request: 
method: GET
uri: /gists?since=0
headers: 
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 



fail: POST (201) /gists?since=0 duration: NaNms
fail: Gists Collection > Create a Gist
request: 
method: POST
uri: /gists?since=0
headers: 
    Content-Type: application/json
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 
{
  "description": "Gist description...",
  "content": "String content..."
}


fail: PUT (204) /gists/42/star duration: NaNms
fail: Star > Star a Gist
request: 
method: PUT
uri: /gists/42/star
headers: 
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 



fail: DELETE (204) /gists/42/star duration: NaNms
fail: Star > Unstar a Gist
request: 
method: DELETE
uri: /gists/42/star
headers: 
    User-Agent: Dredd/11.2.11 (Darwin 18.6.0; x64)

body: 
...
```

**Comment by honzajavorek** [comment]
Hi @EduardoAC, just install MongoDB, the app is able to auto-provision the schema on first connection. This is how it works in the Continuous Integration here as well. If you're using macOS, follow [this tutorial](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/) and then try running the example.

**Comment by honzajavorek** [comment]
I hope my answer helped. @EduardoAC let us know if you still have issues with this. Thanks!
